#!/bin/sh

apt update
apt upgrade -y
apt install git zsh curl -y
apt install powerline fonts-powerline -y
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
chsh -s /bin/zsh